name: general_repository
description: A general api repository to handle API responses
version: 0.0.2
homepage: https://github.com/alimehdirazab/general_repository
repository: https://github.com/alimehdirazab/general_repository.git

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
